package controller.view;

import java.net.URL;
import java.util.ResourceBundle;

import controller.facade.ControleAgendaFacade;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import model.ItemPedidoJoinItem;
import model.Pedido;

@SuppressWarnings("rawtypes")
public class controleAgendaController implements Initializable {
	@FXML
	private TableView tabelaDataPedido;
	@FXML
	private TableColumn colunaEmpresa;
	@FXML
	private TableColumn colunaData;
	@FXML
	private TableColumn colunaStatusPedido;
	@FXML
	private TableView tabelaItensPedido;
	@FXML
	private TableColumn colunaDescricao;
	@FXML
	private TableColumn colunaCusto;
	@FXML
	private TableColumn colunaQuantidade;
	@FXML
	private Button btnSalvar;
	@FXML
	private Button btnSalvar1;

	private ControleAgendaFacade controleAgendaFacade = new ControleAgendaFacade();
	private int selectedRow = -1;

	@SuppressWarnings("unchecked")
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		tabelaDataPedido.setItems(atualizarTabelaPedidos());
		colunaEmpresa.setCellValueFactory(new PropertyValueFactory<Pedido, Integer>("empresa_idEmpresa"));
		colunaData.setCellValueFactory(new PropertyValueFactory<Pedido, String>("data"));
		colunaStatusPedido.setCellValueFactory(new PropertyValueFactory<Pedido, String>("status"));
		btnSalvar.setDisable(true);
		btnSalvar1.setDisable(true);
	}

	public ObservableList<Pedido> atualizarTabelaPedidos() {
		return controleAgendaFacade.atualizarListaPedidos();
	}

	public ObservableList<ItemPedidoJoinItem> atualizarTabelaItensPedido() {
		return controleAgendaFacade.atualizarListaItemPedidos(tabelaDataPedido.getSelectionModel().getSelectedIndex());
	}

	// Event Listener on TableView[#tabelaDataPedido].onMouseClicked
	@SuppressWarnings("unchecked")
	@FXML
	public void selecionaPedido(MouseEvent event) {
		// TODO Autogenerated
		if (tabelaDataPedido.getSelectionModel().getSelectedIndex() >= 0) {
			selectedRow = tabelaDataPedido.getSelectionModel().getSelectedIndex();
			btnSalvar.setDisable(false);
			btnSalvar1.setDisable(false);
			tabelaItensPedido.setItems(atualizarTabelaItensPedido());
			colunaDescricao.setCellValueFactory(new PropertyValueFactory<Pedido, String>("descricao"));
			colunaCusto.setCellValueFactory(new PropertyValueFactory<Pedido, String>("preco"));
			colunaQuantidade.setCellValueFactory(new PropertyValueFactory<Pedido, String>("quantidade"));
		}
	}

	// Event Listener on Button[#btnSalvar].onAction
	@FXML
	public void btnSalvarClicked(ActionEvent event) {
		// TODO Autogenerated
		controleAgendaFacade.statusFinalizado(selectedRow);
		atualizarTabelaPedidos();
		selectedRow = -1;
		btnSalvar.setDisable(true);
		btnSalvar1.setDisable(true);
	}
	
	public void btnSalvar1Clicked(ActionEvent event) {
		// TODO Autogenerated
		controleAgendaFacade.statusLido(selectedRow);
		atualizarTabelaPedidos();
		selectedRow = -1;
		btnSalvar.setDisable(true);
		btnSalvar1.setDisable(true);
	}
}
