package controller.view;

import java.net.URL;
import java.util.ResourceBundle;

import controller.facade.ControleAssociadosFacade;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import model.ItemEmpresaJoinItem;

@SuppressWarnings("rawtypes")
public class controleClientesController implements Initializable {
	@FXML
	private TableView tabelaItens;
	@FXML
	private TableColumn columnDescricao;
	@FXML
	private TableColumn columnAssociado;
	@FXML
	private ComboBox<String> boxEmpresas;
	@FXML
	private Button btnMarcarTodos;
	@FXML
	private Button btnMarcarSelecionado;

	private ControleAssociadosFacade controleAssociadosFacade = new ControleAssociadosFacade();
	private String[] empresaSelecionada = new String[2];
	private Boolean marcarSelecionado = false;

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		boxEmpresas.setItems(controleAssociadosFacade.atualizarEmpresas());
		boxEmpresas.setValue("1 - admin");
	}

	@SuppressWarnings("unchecked")
	public void atualizarTabela(int i) {
		try {
			tabelaItens.setItems(controleAssociadosFacade.atualizarLista(i));
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			System.out.print(empresaSelecionada[1]);
		}
		columnDescricao.setCellValueFactory(new PropertyValueFactory<ItemEmpresaJoinItem, String>("descricao"));
		columnAssociado.setCellValueFactory(new PropertyValueFactory<ItemEmpresaJoinItem, Boolean>("associado"));
	}

	// Event Listener on ComboBox[#boxEmpresas].onAction
	@FXML
	public void boxEmpresasClicked(ActionEvent event) {
		// TODO Autogenerated
		empresaSelecionada = boxEmpresas.getValue().split(" - ");
		if (Integer.parseInt(empresaSelecionada[0]) == 1) {
			atualizarTabela(-1);
		} else {
			atualizarTabela(Integer.parseInt(empresaSelecionada[0]));
		}
	}

	// Event Listener on Button[#btnMarcarTodos].onAction
	@SuppressWarnings("unchecked")
	@FXML
	public void btnMarcarTodosClicked(ActionEvent event) {
		// TODO Autogenerated
		tabelaItens.setItems(controleAssociadosFacade.marcarTodos(true));
		controleAssociadosFacade.salvar();
		atualizarTabela(Integer.parseInt(empresaSelecionada[0]));
	}

	@SuppressWarnings("unchecked")
	@FXML
	public void btnMarcarSelecionadoClicked(ActionEvent event) {
		// TODO Autogenerated
		if (!marcarSelecionado) {
			tabelaItens.setItems(controleAssociadosFacade.marcarSelecionado(marcarSelecionado,
					tabelaItens.getSelectionModel().getSelectedIndex()));
			marcarSelecionado = true;
		} else {
			if (marcarSelecionado) {
				tabelaItens.setItems(controleAssociadosFacade.marcarSelecionado(marcarSelecionado,
						tabelaItens.getSelectionModel().getSelectedIndex()));
				marcarSelecionado = false;
			}
		}
		controleAssociadosFacade.salvar();
		atualizarTabela(Integer.parseInt(empresaSelecionada[0]));
	}
}
