package controller.view;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import controller.singleton.UsuarioLogado;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.control.TextArea;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class homeController implements Initializable {
	@FXML
	private Button btnHome;
	@FXML
	private Button btnPedidos;
	@FXML
	private Button btnControleAdmin;
	@FXML
	private Button btnControleAgenda;
	@FXML
	private Button btnControleAvisos;
	@FXML
	private Button btnCadastroUsuario;
	@FXML
	private Button btnControleClientes;
	@FXML
	private Button btnControleItens;
	@FXML
	private Button btnRelatorios;
	@FXML
	private TabPane tabPane = new TabPane();
	@FXML
	private Tab tabHome = new Tab();
	@FXML
	private Pane home;
	@FXML
	private Button btnLogout;
	@FXML
	private Label txtUsuarioAtivo;
	@FXML
	private TextArea txtAvisos;

	private Boolean admin = false;
	private Boolean adminMenuShow = false;
	private Tab tabControleUsuario = new Tab();
	private Tab tabPedidos = new Tab();
	private Tab tabControleAgenda = new Tab();
	private Tab tabControleDados = new Tab();
	private Tab tabControleClientes = new Tab();
	private Tab tabControleItens = new Tab();
	private Tab tabControleRelatorios = new Tab();

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		txtUsuarioAtivo.setText("Conectado como #" + UsuarioLogado.getUsuario().getLogin());
		if (UsuarioLogado.getUsuario().getPapel().contains("admin")) {
			admin = true;
			txtAvisos.setText("SupplyC v0.0.8 \nUltima Atualização: \n" + "Adicionada tela de edição de pedidos para\n"
					+ "Usuarios não Administradores\n\n\n" + "SupplyC v0.0.7 \nUltima Atualização: \n"
					+ "Corrigida tela de login\n\n\n" + "SupplyC v0.0.6 \nUltima Atualização: \n"
					+ "Adicionado Sistema de Avisos\n\n\n");
		}
		if (!admin) {
			btnControleAdmin.setVisible(false);
			txtAvisos.setText(UsuarioLogado.getEmpresa().getAviso());
		}
	}

	// Event Listener on Button[#btnHome].onAction
	@FXML
	public void btnHomeClicked(ActionEvent event) {
		// TODO Autogenerated
		if (!tabPane.getTabs().contains(tabHome)) {
			tabPane.getTabs().add(tabHome);
			tabPane.getSelectionModel().select(tabHome);
		} else {
			tabPane.getSelectionModel().select(tabHome);
		}
	}

	// Event Listener on Button[#btnPedidos].onAction
	@FXML
	public void btnPedidosClicked(ActionEvent event) {
		if (admin) {
			if (!tabPane.getTabs().contains(tabPedidos)) {
				try {
					tabPedidos.setText("Pedidos");
					tabPedidos.setClosable(true);
					tabPedidos.setId("Pedidos");
					tabPedidos.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/controlePedidos.fxml")));
					tabPane.getTabs().add(tabPedidos);
					tabPane.getSelectionModel().select(tabPedidos);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			} else {
				tabPane.getSelectionModel().select(tabPedidos);
			}
		} else {
			if (!tabPane.getTabs().contains(tabPedidos)) {
				try {
					tabPedidos.setText("Pedidos");
					tabPedidos.setClosable(true);
					tabPedidos.setId("Pedidos");
					tabPedidos.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/pedidos.fxml")));
					tabPane.getTabs().add(tabPedidos);
					tabPane.getSelectionModel().select(tabPedidos);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			} else {
				tabPane.getSelectionModel().select(tabPedidos);
			}
		}
	}

	// Event Listener on Button[#btnControleAgenda].onAction
	@FXML
	public void btnControleAgendaClicked(ActionEvent event) {
		if (!tabPane.getTabs().contains(tabControleAgenda)) {
			try {
				tabControleAgenda.setText("Agenda");
				tabControleAgenda.setClosable(true);
				tabControleAgenda.setId("Agenda");
				tabControleAgenda.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/controleAgenda.fxml")));
				tabPane.getTabs().add(tabControleAgenda);
				tabPane.getSelectionModel().select(tabControleAgenda);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			tabPane.getSelectionModel().select(tabControleAgenda);
		}
	}

	// Event Listener on Button[#btnControleDados].onAction
	@FXML
	public void btnControleAvisosClicked(ActionEvent event) {
		if (!tabPane.getTabs().contains(tabControleDados)) {
			try {
				tabControleDados.setText("Dados");
				tabControleDados.setClosable(true);
				tabControleDados.setId("Dados");
				tabControleDados.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/controleDados.fxml")));
				tabPane.getTabs().add(tabControleDados);
				tabPane.getSelectionModel().select(tabControleDados);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			tabPane.getSelectionModel().select(tabControleDados);
		}
	}

	public void btnControleAdminClicked(ActionEvent event) {
		try {
			if (!adminMenuShow) {
				btnCadastroUsuario.setVisible(true);
				btnControleAgenda.setVisible(true);
				btnControleClientes.setVisible(true);
				btnControleItens.setVisible(true);
				adminMenuShow = true;
			} else {
				btnCadastroUsuario.setVisible(false);
				btnControleAgenda.setVisible(false);
				btnControleAvisos.setVisible(false);
				btnControleClientes.setVisible(false);
				btnControleItens.setVisible(false);
				btnRelatorios.setVisible(false);
				adminMenuShow = false;
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btnControleDatas].onAction
	@FXML
	public void btnCadastroUsuarioClicked(ActionEvent event) {
		if (!tabPane.getTabs().contains(tabControleUsuario)) {
			try {
				tabControleUsuario.setText("Usuarios");
				tabControleUsuario.setClosable(true);
				tabControleUsuario.setId("Usuarios");
				tabControleUsuario
						.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/controleUsuario.fxml")));
				tabPane.getTabs().add(tabControleUsuario);
				tabPane.getSelectionModel().select(tabControleUsuario);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			tabPane.getSelectionModel().select(tabControleUsuario);
		}
	}

	@FXML
	public void btnControleClientesClicked(ActionEvent event) {
		if (!tabPane.getTabs().contains(tabControleClientes)) {
			try {
				tabControleClientes.setText("Empresas");
				tabControleClientes.setClosable(true);
				tabControleClientes.setId("Empresas");
				tabControleClientes
						.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/controleClientes.fxml")));
				tabPane.getTabs().add(tabControleClientes);
				tabPane.getSelectionModel().select(tabControleClientes);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			tabPane.getSelectionModel().select(tabControleClientes);
		}
	}

	@FXML
	public void btnControleItensClicked(ActionEvent event) {
		if (!tabPane.getTabs().contains(tabControleItens)) {
			try {
				tabControleItens.setText("Itens");
				tabControleItens.setClosable(true);
				tabControleItens.setId("Itens");
				tabControleItens.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/controleItens.fxml")));
				tabPane.getTabs().add(tabControleItens);
				tabPane.getSelectionModel().select(tabControleItens);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			tabPane.getSelectionModel().select(tabControleItens);
		}
	}

	// Event Listener on Button[#btnRelatorios].onAction
	@FXML
	public void btnRelatoriosClicked(ActionEvent event) {
		if (!tabPane.getTabs().contains(tabControleRelatorios)) {
			try {
				tabControleRelatorios.setText("Relatorios");
				tabControleRelatorios.setClosable(true);
				tabControleRelatorios.setId("Relatorios");
				tabControleRelatorios
						.setContent(FXMLLoader.load(getClass().getResource("/view/fxml/controleRelatorios.fxml")));
				tabPane.getTabs().add(tabControleRelatorios);
				tabPane.getSelectionModel().select(tabControleRelatorios);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			tabPane.getSelectionModel().select(tabControleRelatorios);
		}
	}

	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void btnLogoutClicked(ActionEvent event) {
		// Cod Logout Here
		Stage primaryStage = new Stage();
		UsuarioLogado.setUsuarioNull();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("/view/fxml/login.fxml"));
			Scene scene = new Scene(root);
			primaryStage.setTitle("SupplyC");
			primaryStage.setScene(scene);
			primaryStage.setResizable(false);
			primaryStage.show();
		} catch (Exception e) {
			e.printStackTrace();
		}
		Stage stage = (Stage) btnLogout.getScene().getWindow();
		stage.close();
	}
}
