package controller.view;

import javax.swing.JOptionPane;

import controller.facade.LoginFacade;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import javafx.stage.Stage;

public class loginController {
	@FXML
	private TextField txtLogin;
	@FXML
	private PasswordField txtSenha;
	@FXML
	private Button btnLogin;

	private LoginFacade facade = new LoginFacade();

	// Event Listener on TextField[#txtLogin].onKeyPressed
	@FXML
	public void txtLoginKeyPressed(KeyEvent event) {
		// TODO Autogenerated
		if (event.getCode() == KeyCode.ENTER) {
			txtSenha.requestFocus();
		}
	}

	// Event Listener on PasswordField[#txtSenha].onKeyPressed
	@FXML
	public void txtSenhaKeyPressed(KeyEvent event) {
		// TODO Autogenerated
		if (event.getCode() == KeyCode.ENTER) {
			btnLogin.requestFocus();
		}
	}

	// Event Listener on Button[#btnLogin].onKeyPressed
	@FXML
	public void btnEntrarKeyPressed(KeyEvent event) {
		// TODO Autogenerated
		if (facade.login(txtLogin.getText(), txtSenha.getText())) {
			Stage stage = (Stage) btnLogin.getScene().getWindow();
			stage.close();
		} else {
			clear();
			JOptionPane.showMessageDialog(null, "Usuario não cadastrado!");
		}
	}

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void btnLoginClicked(ActionEvent event) {
		if (facade.login(txtLogin.getText(), txtSenha.getText())) {
			Stage stage = (Stage) btnLogin.getScene().getWindow();
			stage.close();
		} else {
			clear();
			JOptionPane.showMessageDialog(null, "Usuario não cadastrado!");
		}
	}

	public void clear() {
		txtLogin.clear();
		txtSenha.clear();
		txtLogin.requestFocus();
	}
}
